services:
  db:
    image: pgvector/pgvector:0.6.2-pg16
    container_name: tuki-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tuki_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: tuki
    ports:
      - "8000:8000"
    environment:
        - PYTHONUNBUFFERED=1
        - OMP_NUM_THREADS=1
        - MKL_NUM_THREADS=1
        - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/tuki_db
    volumes:
      - /mnt/c/Users/HP/Desktop/code/TUKI/vault:/app/vault
      - /mnt/c/Users/HP/Desktop/code/TUKI/draft:/app/draft
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
